version: "3.2"
services:
  validator_1:
    container_name: validator_1
    image: centrifugeio/polkadot:chachacha
    ports:
      - "30335:30335"
      - "9933:9933"
      - "9944:9944"
    command: bash -c "polkadot --unsafe-ws-external --rpc-cors all --wasm-execution Compiled --rpc-external --rpc-methods Unsafe --validator --name kylin-validator-1 --ws-port 9944 --port 30335 --rpc-port 9934 --chain rococo-chachacha.json"
    volumes:
      - "polkadot_validator_1:/data"
      - "./rococo-chachacha.json:/rococo-chachacha.json"
  validator_2:
    container_name: validator_2
    image: centrifugeio/polkadot:chachacha
    ports:
      - "30336:30335"
      - "9934:9933"
      - "9945:9944"
    command: bash -c "polkadot --unsafe-ws-external --rpc-cors all --wasm-execution Compiled --rpc-external --rpc-methods Unsafe --validator --name kylin-validator-2 --ws-port 9944 --port 30335 --rpc-port 9934 --chain rococo-chachacha.json"
    volumes:
      - "polkadot_validator_2/:/data"
      - "./rococo-chachacha.json:/rococo-chachacha.json"
volumes:
  polkadot_validator_1:
  polkadot_validator_2: